<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
	$goodwin_helper = $this->helper('Redgiant\Goodwin\Helper\Data');
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
<?php if ($block->isHomePage()): ?>
    <strong class="logo">
<?php else: ?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php echo $storeName; ?>">
<?php endif; ?>
<?php if($goodwin_helper->getConfig('goodwin_settings/header/sticky_header')): ?>
<?php
$sticky_logo_src = "";
if($logo_src = $goodwin_helper->getConfig('goodwin_settings/header/sticky_header_logo_src')) {
    $folderName = \Redgiant\Goodwin\Model\Config\Backend\Image\Stickylogo::UPLOAD_DIR;
    $path = $folderName . '/' . $logo_src;
    $sticky_logo_src = $goodwin_helper->getBaseUrl() . $path;
} else {
	$sticky_logo_src = $block->getLogoSrc();
}
?>
        <img class="sticky-logo" src="<?php echo $sticky_logo_src; ?>"
             alt="<?php echo $block->getLogoAlt(); ?>"
        />
<?php endif; ?>
        <img class="default-logo" src="<?php echo $block->getLogoSrc(); ?>"
             alt="<?php echo $block->getLogoAlt(); ?>"
        />
<?php if ($block->isHomePage()): ?>
    </strong>
<?php else: ?>
    </a>
<?php endif; ?>