<?php
	$_helper = $this->helper('Redgiant\Goodwin\Helper\Data');
	$_product_helper = $this->helper('Magento\Catalog\Helper\Data');
	
	$product = $_product_helper->getProduct();

	$product_page_type = $product->getData('goodwin_product_page_layout');
    if(!$product_page_type)
        $product_page_type = $_helper->getConfig('goodwin_settings/product/product_page_layout');
    if(empty($product_page_type))
        $product_page_type = 'default';
    $current_page = $this->getRequest()->getFullActionName();
?>
<?php if($current_page != 'weltpixel_quickview_catalog_product_view'): ?>
    <?php if($product_page_type == 'default' || $product_page_type == 'vertical_gallery'): ?>
    <div class="product-page-side">
    <?php
        $static_block = $_helper->getConfig('goodwin_settings/product/content_cms_block');
        if (isset($static_block) && $static_block) {
            $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
            if ($block) {
                $block->setBlockId($static_block);
            }
            if ($block) {
                echo '<div class="goodwin-custom-block">' . $block->toHtml() . '</div>';
            }
        }
    ?>
    <script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function(){
            //$(".product-page-side").prepend($(".block.upsell").detach());
            $(".product-page-side").append($(".rg-dailydeal-wrapper").detach());
        });
    });
    </script>
    </div>
    <?php endif; ?>
    <?php if($product_page_type == 'fixed_content'): ?>
    <div class="product-media-bottom">
        <?php
            $static_block = $_helper->getConfig('goodwin_settings/product/content_cms_block');
            if (isset($static_block) && $static_block) {
                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                if ($block) {
                    $block->setBlockId($static_block);
                }
                if ($block) {
                    echo '<div class="goodwin-custom-block">' . $block->toHtml() . '</div>';
                }
            }
        ?>
    </div>
    <script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function(){
            $(".product.media").append($(".product-media-bottom").detach());
            if($(window).innerWidth() >= 992) {
                $(".product.media").append($(".product.info.detailed").detach());     
            }
        });
        $(window).resize(function(){
            if($(window).innerWidth() >= 992) {
                $(".product.media").append($(".product.info.detailed").detach());     
            }else{
                $(".product-info-container").after($(".product.info.detailed").detach());
            }
        });
    });
    </script>
    <?php endif; ?>
<?php endif; ?>