<?php
$configurationData = $this->getStoreConfigurationData();
$storeList = $this->getStoresList();
$mediaPath = $this->getMediaBaseUrl();
$weekDays = $this->getWeekList();
$placeHolder = $this->getPlaceholderImage();
$postData = $this->getPostParams();
$location = $this->getMapSession();
$minRange = $configurationData['min-range'];
$maxRange = $configurationData['max-range'];
$averageRange = $configurationData['average-range'];
$getMainStore = $this->getMainStoreDetails();
$countryList = $this->getCountryList();
?>
<div class="home-locations">
	<div class="locations">
		<div class="lcontainer-fluid locations__container has-carousel">
			<div class="locations__wrapper row">
				<div class="locations_form col-md-4">
					<div class="box_header">
						<header class="locations__header text-center"><h3 class="locations__title">Store Locations</h3><p class="locations__subtitle">Come in for a mattress buying experience unlike any other!</p>
						</header>
						<form class="locations-form">
							<input name="zip" placeholder="enter zip code" type="number" class="input locations-form__input">
							<button type="submit" class="locations-find" style="display: none;"></button>
						</form>
						<div class="text-center">
							<a href="/wbstore/store/index" class="btn btn-locations" title="locations"><span class="btn__label">All Locations</span></a>
						</div>
					</div>
				</div>
				<div class="locations__items col-md-8">
					<div class="locations__carousel flickity-enabled is-draggable" tabindex="0">
						<div class="flickity-viewport" style="height: 523px; touch-action: pan-y;">
							<div class="flickity-slider" style="left: 0px;">
								<?php if(!empty($storeList)) {?>
								<div class="stores-carousel js-brand-carousel slick-arrows-aside-simple" data-slick='{"slidesToShow": 3, "slidesToScroll": 2}'>
					                <?php foreach ($storeList as $key => $data) {
					                    $storeWorking = (array) json_decode($data['working_days']);
					                    $date = date('Y-m-d H:i:s');
					                    $day = date('D', strtotime($date));
					                    $dayVal = $weekDays[$day];
					                    $status = 'close';
					                    $check = $dayVal.'_check';
					                    if (array_key_exists($check,$storeWorking)){
					                        $status = $storeWorking[$check];
					                    }
					                    $openTime  = $storeWorking[$dayVal.'_opening_time'];
					                    $closeTime  = $storeWorking[$dayVal.'_closing_time'];
					                    ?>
		                     		<div>
						            	<article class="location">
											<div class="location_wrapper">
												<a href="/wbstore/store/index" title="<?= $data['store_name'];?>">
                                                    <div class="location__map ir ir--map show-pc">
                                                        <?php if((isset($data['image'])) && (!empty($data['image']))) { ?>
                                                            <img src="<?= $mediaPath.$data['image']?>" class="wb-image" alt="<?= $data['store_name'];?>">
                                                        <?php } else {?>
                                                            <?= $placeHolder;?>
                                                        <?php }?>
                                                    </div>
                                                    <div class="location__map ir ir--map show-desktop">
                                                        <?php if((isset($data['imagelap'])) && (!empty($data['imagelap']))) { ?>
                                                            <img src="<?= $mediaPath.$data['imagelap']?>" class="wb-image" alt="<?= $data['store_name'];?>">
                                                        <?php } else {?>
                                                            <?= $placeHolder;?>
                                                        <?php }?>
                                                    </div>
                                                </a>
												<div class="location_details">
													<a href="/wbstore/store/index" title="location">
														<h5 class="location_title"><?= $data['store_name'];?></h5></a>
														<address class="location_address">
															<span class="location_address location_address-street"><?= $data['address']?></span>
													    </address>
                                                        <address class="location_address">
                                                            <span class="location_address location_address-street"><?= $data['city']?>,<?= $data['state']?> <?= $data['zipcode']?></span>
                                                        </address>
													    <a href="tel:<?= $data['contact_no']?>" class="location_phone" title="phone"><?= $data['contact_no']?></a>
													<div class="location__hours">
                                                        <p><strong>Mon - Sunday</strong> 10am - 7pm</p>
													</div>
													<div class="location__link-wrap">
														<a href="/wbstore/store/index" class="location__directions location__directions--details" title="view map"><span class="btn-decor btn-decor--xs bnr-btn">view map<span class="btn-line"></span></span></a>
													</div>
												</div>
											</div>
										</article>
						            </div>
					                <?php }?>
					            	<?php } else{?>
					                <div class="no-store">
					                    <?php if ((!empty($postData)) && (isset($postData['store-text']))){
					                        echo 'No store is found with searching keyword, currently our main store visible on map';
					                    } else{
					                        echo 'No Store Found.';
					                    }
					                    ?>
					                </div>
					            	<?php }?>
								</div>
							</div>
						</div>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>

<div class="wb-store-contents">
    <div class="wb-store-listing-main">
        <div class="wb-store-details wb-listing">
        </div>
    </div>
</div>

<script>
    require([
    'jquery',
    'slick-skin'
    ], function ($, slickcarousel) {
         slickcarousel.init('.stores-carousel');
    });
</script>