<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <div class="post-content">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-ftimg-hld">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </a>
            </div>
        <?php } ?>
        <?php echo $this->getInfoHtml() ?>
        <h2 class="post-title">
            <a class="post-item-link"
                href="<?php echo $_postUrl ?>">
                <?php echo $_postName; ?>
            </a>
        </h2>
        <div class="post-description clearfix">
            <div class="post-text-hld clearfix">
                <?php echo $block->getShorContent() ?>
            </div>
        </div>
    </div>
    <div class="post-footer">
        <div class="item post-posed-date">
            <span class="label"><?php echo __('Posted:') ?></span>
            <span class="value"><?php echo $_post->getPublishDate('F d, Y') ?></span>
        </div>
        <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
            <?php echo __('Read more') ?>
        </a>
        <div class="addthis_toolbox addthis_default_style"
            addthis:url="<?php echo $_postUrl ?>"
            addthis:title="<?php echo $_postName; ?>"
            <?php if ($firstImage = $_post->getFirstImage()) { ?>
            addthis:media="<?php echo $firstImage ?>"
            <?php } ?>>
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_email"></a>
            <a class="addthis_button_compact"></a>
        </div>
    </div>
</li>