<?php
    $_helper = $this->helper('Redgiant\Goodwin\Helper\Data');
    $contacts_config = $_helper->getConfig('goodwin_settings/contacts');
    $_infoblock2 = $contacts_config['infoblock2'];
    $_type = (int)$contacts_config["contacts_type"];
    
?>
<div class="contact-us-type<?php echo $_type; ?> contact-us-page">
    <div class="container">
        <div class="row vert-margin-double justify-content-center">
            <div class="col-sm-6 col-lg-4">
                <?php echo $_helper->filterContent($_infoblock2); ?>
            </div>
            <div class="col-sm-6 col-lg-4 offset-lg-1">
                <?php echo $this->getChildHtml('contactForm')?>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml('google_map')?>
</div>