<?php
    $_helper = $this->helper('Redgiant\Goodwin\Helper\Data');
    $contacts_config = $this->getConfig('goodwin_settings/contacts');
    $_enable = $contacts_config['enable'];
    $type = (int)$contacts_config["contacts_type"];
    
    if($_enable):
        $_apikey = $contacts_config['api_key'];
        $_zoom = $contacts_config['zoom'];
        $_center_lat = $contacts_config['latitude'];
        $_center_lng = $contacts_config['longitude'];
        $_infoblock1 = $contacts_config['infoblock1'];
        $_fullwidth = $contacts_config['full_width'];

        $pin_marker = $_helper->getBaseUrl() . 'wysiwyg/goodwin/googlemap/map-icon.png';
?>
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?<?php if($_apikey): ?>key=<?php echo $_apikey; ?><?php else: ?>v=3.17<?php endif; ?>"></script>
<script type="text/javascript">
    function initialize() {
        var pos = new google.maps.LatLng(<?php echo $_center_lat; ?>, <?php echo $_center_lng; ?>);
        var mapOptions = {
            center: pos,
            panControl: true,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            overviewMapControl: true,            
            zoom: <?php echo $_zoom; ?>
        };
        var map = new google.maps.Map(document.getElementById("store_map"), mapOptions);
        var marker = new google.maps.Marker({
            position: pos,
            map: map,
            icon: '<?php echo $pin_marker; ?>',
            title: 'Goodwin'
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div class="holder">
    <?php echo $_helper->filterContent($_infoblock1); ?>
    <div id="store_map" class="map-container map-type<?php echo $type; ?>"></div>
</div>
<?php  endif; ?>
