<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 

$dailydealhelper=$this->helper('Redgiant\Dailydeals\Helper\Data'); 

?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <?php if($block->getRequest()->getParam('dailydealproduct') || $dailydealhelper->isDealProduct($_product->getId())) : ?>
        <div class="rg-dailydeal-wrapper" style="display:none;" data-to-date="<?php echo $_dailydealhelper->getDailydealToDate($_product->getSku()); ?>">
            <div class="rg-dailydeal">
                <?php if($block->getRequest()->getParam('dailydealproduct')) :?>
                    <p class="expired"></p> 
                <?php endif; ?> 
                <div class="countdowncontainer" style="display:none;">
                    <span class="dailydeal-label">
                        <?php echo __('Offer Ends In:'); ?>
                    </span>
                    <span class="number-wrapper">
                        <span class="number day"><span>00</span></span>
                        <span class="caption"><?php echo __('days'); ?></span>
                    </span>

                    <span class="number-wrapper">
                        <span class="number hour"><span>00</span></span>
                        <span class="caption"><?php echo __('hrs'); ?></span>
                    </span>

                    <span class="number-wrapper">
                        <span class="number min"><span>00</span></span>
                        <span class="caption"><?php echo __('min'); ?></span>
                    </span>

                    <span class="number-wrapper">
                        <span class="number sec"><span>00</span></span>
                        <span class="caption"><?php echo __('sec'); ?></span>
                    </span>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<script type="text/javascript">
    require([
        'jquery', 'rgDailydeals'     
    ], function ($) {
        $.fn.rg_dailydeal_init('.rg-dailydeal-wrapper', '<?php echo $dailydealhelper->getcurrentDate() ?>');
    });   
</script>