<?php
/**
 */
?>
<?php if ($block->canShowBlock()): ?>
    <?php
    $filters     = $block->getFilters();
    $layerConfig = $this->helper('Redgiant\LayeredNavigation\Helper\Data')->getLayerConfiguration($filters);
    $filtered    = count($block->getLayer()->getState()->getFilters());
    ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <a href="javascript:void(0)" class="filter-close"><?php echo __('Close') ?></a>
        
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */
        echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Filters') ?></strong>
        </div>
        
        <div class="block-content filter-content" data-mage-init='{"rgLayer": <?php echo $layerConfig ?>}'>
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */
                    echo $block->getClearUrl() ?>"
                       class="action clear filter-clear"><span><?php /* @escapeNotVerified */
                            echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>

            <?php $wrapOptions = false; ?>
            <?php foreach ($filters as $key => $filter): ?>
        <?php if ($filter->getItemsCount()): ?>
        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2"
                    class="block-subtitle filter-subtitle"><?php echo __('Shopping Options') ?></strong>
            <div class="filter-options" id="narrow-by-list" data-role="content">
                <?php $wrapOptions = true;
                endif; ?>
                <?php /*if($filter->getRequestVar() == 'cat'){ continue; }*/ $_class = 'active'; ?>
                <div class="filter-options-item <?php echo $_class; ?>"
                     attribute="<?php echo $filter->getRequestVar() ?>">
                    <div class="filter-options-title"><?php /* @escapeNotVerified */
                        echo __($filter->getName()) ?></div>
                    <div class="filter-options-content"><?php /* @escapeNotVerified */
                        echo $block->getChildBlock('renderer')->setFilter($filter)->render($filter); ?></div>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </div>
        <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
            <?php endif; ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $(document).ready(function(){
                        if ($('body').hasClass('page-layout-1column')) {
                            var toolbar = $('div#layer-product-list .toolbar-products');
                            if(toolbar.length > 1) {
                                toolbar.first().prependTo('.layered-filter-block-container');
                            }else {
                                toolbar.prependTo('.layered-filter-block-container');
                            }
                            $('.filter-options-item').each(function(){
                                $(this).removeClass('active');
                            });
                            $(".block.filter").toggleClass('active');
                            $(".block.filter .filter-title").on('click', function(){
                                $(".block.filter").toggleClass('active');
                                $('.filter-content').animate({height:"toggle"}, 500);
                            });
                        }
                        var mq = window.matchMedia( "(max-width: 992px)" )
                        if (mq.matches) {
                            $('.filter-options-item').each(function(){
                                $(this).removeClass('active');
                            });
                        }

                        $("#narrow-by-list .filter-options-item").on('click', function(){
                            if ($(this).hasClass('actives')) {
                                $(this).removeClass('actives');
                                $(this).parent().find(".filter-options-content").removeClass('actives');
                            }else{
                                $(this).addClass('actives');
                                $(this).parent().find(".filter-options-content").addClass('actives');
                            }
                        });
                        $("#narrow-by-list .actives").on('click', function(){
                            $(this).removeClass('actives');
                            $(this).parent().find(".filter-options-content").removeClass('actives');

                        });
                    });
                });
            </script>
            <?php echo $block->getChildHtml('layer_additional_info') ?>
        </div>
    </div>
<?php endif; ?>
