<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $block->getProduct();
$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
$_goodwinhelper = $this->helper( 'Redgiant\Goodwin\Helper\Data' ); 
$_sale_label = $_goodwinhelper->getConfig('goodwin_settings/catalog/sale_label');
$_new_label = $_goodwinhelper->getConfig('goodwin_settings/catalog/new_label');
$_show_percent = $_goodwinhelper->getConfig('goodwin_settings/catalog/show_percent');
?>
<?php
    $product_label = "";
    if($_sale_label) {
        $orgprice = $_product->getPrice();
        $specialprice = $_product->getSpecialPrice();
        $specialfromdate = $_product->getSpecialFromDate();
        $specialtodate = $_product->getSpecialToDate();
        $today = time();
        if(!$specialprice)
            $specialprice = $orgprice;
        if($specialprice < $orgprice) {
            if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                $percent = number_format ( ($specialprice - $orgprice) / $orgprice * 100) . '%';
                if($_show_percent) $_sale_label = $percent;
                $product_label .= '<div class="product-label sale-label">';$product_label .= '<span>'. $_sale_label .'</span>';$product_label .= '</div>';
            }
        }
    }
    if($_new_label) {
        $now = date("Y-m-d");
        $newsFrom= substr($_product->getData('news_from_date'),0,10);
        $newsTo=  substr($_product->getData('news_to_date'),0,10);
        if ($newsTo != '' || $newsFrom != ''){
            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                $product_label .= '<div class="product-label new-label">';$product_label .= '<span>'. $_new_label .'</span>';$product_label .= '</div>';
            }
        }
    }
    echo '<div class="product-label-container">' . $product_label . '</div>';
?>