<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */

$_helper = $this->helper('Redgiant\Goodwin\Helper\Data');

?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                <span class="currency-symbol"><?= $_helper->getCurrencySymbol($currentCurrencyCode) ?></span>
                <span class="currency-code"><?= $block->escapeHtml($currentCurrencyCode) ?></span>
            </strong>
        </div>
        <div class="dropdown switcher-dropdown" data-target="dropdown">
            <div class="container">
                <ul>
                <?php foreach ($currencies as $_code => $_name): ?>
                    <?php if ($_code != $currentCurrencyCode): ?>
                        <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                            <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><span class="currency-symbol"><?= $_helper->getCurrencySymbol($_code) ?></span><span class="currency-code"><?= $block->escapeHtml($_code) ?></span><span class="currency-divider">-</span><span class="currency-name"><?= $block->escapeHtml($_name) ?></span></a>
                        </li>
                    <?php else: ?>
                        <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option active">
                            <a href="javascript:void(0)"><span class="currency-symbol"><?= $_helper->getCurrencySymbol($_code) ?></span><span class="currency-code"><?= $block->escapeHtml($_code) ?></span><span class="currency-divider">-</span><span class="currency-name"><?= $block->escapeHtml($_name) ?></span></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
