<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<?php
    $_helper = $this->helper('Redgiant\Goodwin\Helper\Data');
    $is_demo = $_helper->getConfig("goodwin_settings/general/is_demo");
?>
<?php if (count($block->getStores())>1 || $is_demo): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <div class="dropdown switcher-dropdown" data-target="dropdown">
            <div class="container">
                <ul>
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                                <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/goodwin/flags/'.$block->escapeHtml($_lang->getCode()).'.png'; ?>" alt=""/>
                                <span><?= $block->escapeHtml($_lang->getName()) ?></span>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option active">
                            <a href="javascript:void(0)">
                                <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/goodwin/flags/'.$block->escapeHtml($_lang->getCode()).'.png'; ?>" alt=""/>
                                <span><?= $block->escapeHtml($_lang->getName()) ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if($is_demo): ?>
                    <li class="view-spanish switcher-option">
                        <a href="javascript:void(0)">
                            <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/goodwin/flags/spanish.png'; ?>" alt=""/>
                            <span><?php echo __('Spanish'); ?></span>
                        </a>
                    </li>
                    <li class="view-german switcher-option">
                        <a href="javascript:void(0)">
                            <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/goodwin/flags/german.png'; ?>" alt=""/>
                            <span><?php echo __('German'); ?></span>
                        </a>
                    </li>
                    <li class="view-french switcher-option">
                        <a href="javascript:void(0)">
                            <img src="<?php echo $_helper->getBaseUrl().'wysiwyg/goodwin/flags/french.png'; ?>" alt=""/>
                            <span><?php echo __('French'); ?></span>
                        </a>
                    </li>
                <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

